version: '3'

services:
  frontend:
    image: sosci/frontend
    build: 
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - HOST_PORT=34255
      - HOST_ADDRESS=0.0.0.0

    container_name: s-frontend
    restart: always

    networks:
      - internal
      - web
    expose:
      - 34255

    ports:
      - 5000:80

networks:
  internal:
    driver: bridge
    internal: true
  web:
    driver: bridge