version: '3'

services:
  backend:
    image: sosci/backend
    build: 
      context: ./
      dockerfile: ./Dockerfile
    
    container_name: "sosci-backend"
    restart: always

    ports:
      - 9000:34254
