version: '3'

services:
  generator:
    image: sosci/generator:${VERSION_TAG:-latest}
    pull_policy: always
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0:34258
      - TARGET=backend:34259
      - PPS=100.0
      - SIG_FREQ=1.0
    ports:
      - 34258:34258
    networks:
      - internal

  frontend:
    image: sosci/frontend:${VERSION_TAG:-latest}
    pull_policy: always
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - internal
      - web
    labels:
      - "traefik.enable=true"
        # Redirect HTTP
      - "traefik.http.routers.sosci-prod-frontend-web.service=sosci-prod-frontend-websecure"
      - "traefik.http.middlewares.sosci-prod-frontend-websecure.redirectscheme.scheme=https"
      - "traefik.http.routers.sosci-prod-frontend-web.middlewares=sosci-prod-frontend-websecure"
      - "traefik.http.routers.sosci-prod-frontend-web.rule=Host(`amos-sosci.die-degens.eu`)"
      - "traefik.http.routers.sosci-prod-frontend-web.entrypoints=web"
        # HTTPS
      - "traefik.http.routers.sosci-prod-frontend-websecure.rule=Host(`amos-sosci.die-degens.eu`)"
      - "traefik.http.routers.sosci-prod-frontend-websecure.entrypoints=websecure"
      - "traefik.http.routers.sosci-prod-frontend-websecure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.sosci-prod-frontend-websecure.service=sosci-prod-frontend-websecure"
      - "traefik.http.services.sosci-prod-frontend-websecure.loadbalancer.server.port=80"

  backend:
    image: sosci/backend:${VERSION_TAG:-latest}
    pull_policy: always
    environment:
      - HOST_PORT=34259
      - HOST_ADDRESS=0.0.0.0
    ports: 
      - 34259:34259
    networks:
      - internal
      - web
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Remove path prefix
      - "traefik.http.middlewares.sosci-backend-stripprefix-prod.stripprefix.prefixes=/prod/api"
        # Main
      - "traefik.http.routers.sosci-prod-backend.rule=Host(`amos-sosci.die-degens.eu`) && PathPrefix(`/prod/api`)"
      - "traefik.http.routers.sosci-prod-backend.entrypoints=websecure"
      - "traefik.http.routers.sosci-prod-backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.sosci-prod-backend.service=sosci-prod-backend"
      - "traefik.http.services.sosci-prod-backend.loadbalancer.server.port=9000"
      - "traefik.http.routers.sosci-prod-backend.middlewares=sosci-backend-stripprefix-prod"

networks:
  internal:
    driver: bridge
    internal: true
  web:
    driver: bridge
    external: true
