version: '3'

services:
  generator:
    image: sosci/generator
    build: 
      context: ./generator
      dockerfile: Dockerfile
    restart: always
    environment:
      - HOST=0.0.0.0:34254
      - TARGET=backend:34255
      - FREQUENCY=1.0
    ports:
      - 34254:34254
    networks:
      - internal

  frontend:
    image: sosci/frontend
    depends_on:
      - backend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:80
    networks:
      - internal
      - web

  backend:
    image: sosci/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - HOST_PORT=34255
      - HOST_ADDRESS=0.0.0.0
    ports: 
      - 34255:34255
    networks:
      - internal

networks:
  internal:
    driver: bridge
    internal: true
  web:
    driver: bridge
