version: '3'

services:
  generator:
    image: sosci/generator
    build: 
      context: ./generator
      dockerfile: Dockerfile
    restart: always
    environment:
      - HOST=0.0.0.0:34254
      - TARGET=backend:34255
      - FREQUENCY=1.0
    expose:
      - 34254
  frontend:
    image: sosci/frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 5000:80
  backend:
    image: sosci/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - HOST_PORT=34255
      - HOST_ADDRESS=0.0.0.0
    expose: 
      - 34255
