version: '3'

services:
  generator:
    image: sosci/generator
    hostname: generator
    build: 
      context: ./generator
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0:34254
      - TARGET=backend:34255
      - PPS=100000.0
      - SIG_FREQ=1.0
    ports:
      - 34254:34254
    networks:
      - internal

  frontend:
    image: sosci/frontend
    hostname: frontend
    depends_on:
      - backend
    build:
      args:
        MODE: localhost
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5000:80
    networks:
      - internal
      - web

  backend:
    image: sosci/backend
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - HOST_PORT=34255
      - HOST_ADDRESS=0.0.0.0
    ports: 
      - 34255:34255
      - 9000:9000
    networks:
      - internal
      - web
    restart: unless-stopped

networks:
  internal:
    driver: bridge
    internal: true
  web:
    driver: bridge
