version: '3'

services:
  backend:
    depends_on:
      - frontend
    image: sosci/backend
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    
    restart: always

    environment:
      - HOST=0.0.0.0:34254
      - TARGET=frontend:34255
      - FREQUENCY=1.0
    networks:
      - internal

    expose:
      - 34254

  frontend:
    image: sosci/frontend
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - HOST_PORT=34255
      - HOST_ADDRESS=0.0.0.0

    container_name: frontend
    restart: always


    networks:
      - internal
      - web
    expose:
      - 34255

    ports:
      - 5000:80

networks:
  internal:
    driver: bridge
    internal: true
  web:
    driver: bridge

