name: CI Build Docker Frontend

on:
  push:
    branches:
      - "feature/#40-setting-up-cicd"
  pull_request:
    branches: 
      - "dev"
      - "int"
      - "main"
    paths:
      - 'Apps/frontend/*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      -
        if: github.ref_name== 'feature/#40-setting-up-cicd'
        name: Build and push from feature branch
        uses: docker/build-push-action@v3
        with:
          context: ./Apps/frontend
          platforms: linux/amd64
          push: true
          tags: |
            sosci/frontend:nightly
      -
        if: github.event.pull_request.base.ref == 'dev'
        name: Build and push from dev
        uses: docker/build-push-action@v3
        with:
          context: ./Apps/frontend
          platforms: linux/amd64
          push: true
          tags: |
            sosci/frontend:nightly
      -
        if: github.event.pull_request.base.ref == 'int'
        name: Build and push from int
        uses: docker/build-push-action@v3
        with:
          context: ./Apps/frontend
          platforms: linux/amd64
          push: true
          tags: |
            sosci/frontend:${{ github.event.pull_request.title }}
      -
        if: github.event.pull_request.base.ref == 'main'
        name: Build and push from main
        uses: docker/build-push-action@v3
        with:
          context: ./Apps/frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sosci/frontend:${{ github.event.pull_request.title }}
            sosci/frontend:latest