name: CI Build Docker Frontend

on:
  push:
    branches:
      - "feature/#40-setting-up-cicd"
    paths:
      - 'Apps/frontend/**.*'
      - '.github/workflows/build-frontend-automation.yml'
  pull_request:
    branches:
      - "dev"
      - "int"
      - "main"
    paths:
      - 'Apps/frontend/**.*'
      - '.github/workflows/build-frontend-automation.yml'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      -
        if: github.ref_name== 'feature/#40-setting-up-cicd'
        name: Build from feature branch
        uses: docker/build-push-action@v3
        with:
          context: ./Apps/frontend
          platforms: linux/amd64
          build-args: |
            MODE=develop
          push: false
          tags: |
            sosci/frontend:nightly
      -
        if: github.event.pull_request.base.ref == 'dev'
        name: Build from dev
        uses: docker/build-push-action@v3
        with:
          context: ./Apps/frontend
          platforms: linux/amd64
          build-args: |
            MODE=develop
          push: false
          tags: |
            sosci/frontend:nightly
      -
        if: github.event.pull_request.base.ref == 'int'
        name: Build from int
        uses: docker/build-push-action@v3
        with:
          context: ./Apps/frontend
          platforms: linux/amd64
          build-args: |
            MODE=integration
          push: false
          tags: |
            sosci/frontend:${{ github.event.pull_request.title }}
      -
        if: github.event.pull_request.base.ref == 'main'
        name: Build from main
        uses: docker/build-push-action@v3
        with:
          context: ./Apps/frontend
          platforms: linux/amd64
          build-args: |
            MODE=production
          push: false
          tags: |
            sosci/frontend:${{ github.event.pull_request.title }}
            sosci/frontend:latest