name: CI Degen Deployment Trigger

on:
  pull_request:
    types:
      - "completed"
    branches: 
      - "dev"
      - "int"
      - "main"
      
jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    needs:
      - "CI Push Docker Backend"
      - "CI Push Docker Frontend"
      - "CI Push Docker Generator"

    steps:
      - 
        if: github.event.pull_request.base.ref == 'dev'
        name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL_DEV }}?SERVICE_TAG=nightly
      - 
        if: github.event.pull_request.base.ref == 'int'
        name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL_INT }}?SERVICE_TAG=${{ github.event.pull_request.title }}
      - 
        if: github.event.pull_request.base.ref == 'main'
        name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL_PROD }}?SERVICE_TAG=${{ github.event.pull_request.title }}
