name: CI Test Docker Backend

on:
  push:
    paths:
      - 'Apps/backend/**.*'
      - '.github/workflows/test-backend-automation.yml'
  pull_request:
    branches:
      - "dev"
      - "int"
      - "main"

jobs:
  jest-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './Apps/backend'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: npm install
      - name: Execute tests
        run: npm test
      - name: Check Code Coverage
        run: npm run test-cov

