name: CI Test Docker Generator

on:
  push:
    paths:
      - 'Apps/generator/**.*'
      - '.github/workflows/test-generator-codecov.yml'
  pull_request:
    branches:
      - "dev"
      - "int"
      - "main"

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        working-directory: ./Apps/generator
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        working-directory: ./Apps/generator
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true