name: CI Test Docker Backend

on:
  push:
    paths:
      - 'Apps/backend/**.*'
      - '.github/workflows/test-backend-automation.yml'
  pull_request:
    branches:
      - "dev"
      - "int"
      - "main"

jobs:
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Install
        uses: actions/setup-node@v3
        with:
          working-directory: ./Apps/backend
          node-version: 19
      - run: npm install
        working-directory: ./Apps/frontend
      - run: npm run test
        working-directory: ./Apps/frontend

